sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cfCwgjUW0CILjcriCwFNLLqaRPnK08TuT4yHQQbHbooK2aoJelkxovi6DG0RM8m0buYP4hRNim8D9gwC+2Zub4PS6V/2eVWFvylzcIb43dMdYHuRINtsfPh4txeT8xyODNg+rZVtwGc3aHw6/vI1BFeSvaCA/Q6PtqPg5fjj94zW+AFk0Bnjserx62Xal5UC5EEBv/yH70JllNxRBo3ST4B35Kzqg8tW3zksi/lxRoOb25U5Wp9JgPRIjW7NNdDOo6C4ckMBynR8OnqF2mMum4PxYrlrJMiJJxMa1tHauCJmS1MXNe5dXDsGWhkH1f80XGoZ01oiIuEh1iJUA69ZhqdM0WiVmmkEkbV3gs/kv7/rrUHocB8x/xG0xPDNMYrVR/XK7n52zlR00Vz25Dj8t3BCLRWhUTGJ3JZhiVJS3YiEvSFatMt58MIM/m2KH22CWsI5HRw8hruuzNU4+BIlp1j67nC7RTOPU9tMax3MOAN8QGG+lYmHguUHiU6FmEwLWZkQhgIcQoB25gkr/jFmdd1FtMVDCRosVpGVjPnsRcsWFk2umbvxviSNwqBaGuiLZwwLZSo7fh3j8EoMyWR8lVobo+0cTyF0jY65hVQeMXlLjIcibT/wnbzKTO4w+Uo5TI15Xh75D77oDzafOmUOy2lT7G5evPgZ0mAjVpXUxDs=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/In-the-Fire-of-the-Forge-A-Romance-of-Old-Nuremberg-Volume-01_5543
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy